site_name: LAiSER Docs V0.2
theme:
  name: material
  features:
    - content.code.annotate
    - content.code.copy
    - content.tabs.link
    - navigation.tabs
    - navigation.footer
    - navigation.indexes
    - navigation.sections
    - toc.integrate
    - navigation.top
    - navigation.tracking
    - search.suggest
    - search.highlight
    - search.share
  language: en
  palette:
    - scheme: default
      primary: indigo
      toggle:
        icon: material/weather-sunny
        name: Switch to dark mode
      accent: purple 
    - scheme: slate 
      primary: indigo
      accent: deep orange
      toggle:
        icon: material/weather-night
        name: Switch to light mode    
  extra:
    social:
      - icon: fontawesome/brands/mastodon 
        link: https://fosstodon.org/@squidfunk      